import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		int FamiliesOf2Childs = 0;
		int FamiliesOf3Childs = 0;
		int FamiliesOf4OrMoreChilds = 0;
		double sumFamiliesOfChilds = 0;

		for(int i = 0; i < T; i++)
		{
			boolean girl = false;
			boolean boy = false;
			int count = 0;

			while (!(girl && boy))
			{
				double rnd = generator.nextDouble();
				if (rnd < 0.5)
				{
					girl = true;
				}
				else
				{
					boy = true;
				}
				count++;
			}
			sumFamiliesOfChilds = sumFamiliesOfChilds + count;
			if (count == 2) 
			{
				FamiliesOf2Childs++;
			}
			else
			{
				if (count == 3) 
				{
					FamiliesOf3Childs++;
				}
				else
				{
					FamiliesOf4OrMoreChilds++;
				}
			}
			
		}
		double avg = sumFamiliesOfChilds / T;
		System.out.println("Average: " + avg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + FamiliesOf2Childs);
		System.out.println("Number of families with 3 children: " + FamiliesOf3Childs);
		System.out.println("Number of families with 4 or more children: " + FamiliesOf4OrMoreChilds);

		int max = Math.max(Math.max(FamiliesOf2Childs, FamiliesOf3Childs), FamiliesOf4OrMoreChilds);
		String commom = "The most common number of children is ";
		if (max == FamiliesOf2Childs) 
		{
			commom = commom + "2.";
		}
		else
		{
			if (max == FamiliesOf3Childs) 
			{
				commom = commom + "3.";
			}
			else
				{
					commom = commom + "4 or more.";
				}	
		}
			
		System.out.println(commom);
		    
	}
}
